#!/bin/bash

# Associative Arrays must be declared
declare -A fullNames

# then it is indexed like a dict
fullNames=( ["joe"]="Debian Joe" ["ivan"]="David Letters_I_do_not_have" \
["bacon"]="Jules Das Machine")

echo "Current user is: $USER. Full name: ${fullNames[$USER]}."
echo ""

for user in "${!fullNames[@]}"
    do echo "User: $user, fullname: ${fullNames[$user]}."; done

# much like a python dict, the order is unpredictable.
