#!/bin/bash

backs=$(find ./ -name "*~" -print0 | xargs -0)
dotbacks=$(find ./ -name ".*~" -print0 | xargs -0)
scrots=$(find ./ -name "$(date +%Y)*.png")
fbcats=$(find ./ -name "*.ppm")
dumps=$(find ./ -name "core.*" -print0 | xargs -0)

if [ -n "$backs" ]; then
    rm -i $(find ./ -name "*~" -print0 | xargs -0)
elif [ -n "$dotbacks" ]; then
    rm -i $(find ./ -name ".*~" -print0 | xargs -0)
elif [ -n "$scrots" ]; then
    rm -i $(find ./ -name "$(date +%Y)*.png")
elif [ -n "$fbcats" ]; then
    rm -i $(find ./ -name "*.ppm")
elif [ -n "$dumps" ]; then
    rm -i $(find ./ -name "core.*" -print0 | xargs -0)
fi
