#!/bin/bash
# init
FILE="/tmp/out.$$"
GREP="/bin/grep"
#.......

# Make sure that script is running as root

if [[ $EUID -ne 0 ]]; then
    echo "This script must be ran as root" 1>&2
    exit 1
fi

echo "You are now root!!!"
