#!/bin/bash

clear
printf "\033[1;31mSelect Stream\033[1;m\n\n"
printf "choose number and press enter\n"
echo "1) Deep Space 1"
echo "2) Doomed"
echo "3) Folk Forward"
echo "4) Lush"
echo "5) Ambient Sleeping Pill"
echo "6) Cliqhop"
read selection
case $selection in
    "1") #Deepspace
     	mpg123 http://xstream1.somafm.com:2800
	;;
    "2") #Doomed
	$(mpg123 http://xstream1.somafm.com:8300)
	;;
    "3") #FolkForward
	$(mpg123 http://xstream1.somafm.com:7400)
	;;
    "4") #Lush
	$(mpg123 http://uwstream1.somafm.com:8800)
	;;
    "5") #ASP
	$(mpg123 http://50.7.96.138:8530/stream)
	;;
    "6") #Cliqhop
	$(mpg123 http://xstream1.somafm.com:8062)
	;;
    *)
	echo "not a valid stream"

esac
