#!/bin/bash

#Pipes are easy, they're just using the output of one program as the input for another.
ls -l | sed -e "s/[aeio]/u/g"

#Local variables in bash:

HELLO=Hello
function hello {
	local HELLO=World
	echo $HELLO
}
echo $HELLO
hello
echo $HELLO

#Builtins: Bash has some basic commands built in.
#Keywords Keywords are like builtins, but have different parsing rules.
#[ is a builtin
#[[ is a bash keyword

#To determine the difference, you can use the 'type' command

#ie: type rm or type cd...rm is hashed, while cd is a builtin
