#!/bin/bash

KITTY="kitty"

echo $KITTY
echo "Hello $KITTY" | sed s/kitty/world/
echo $KITTY | sed 's/[a-z]*/(&)/'

echo "$KITTY 123" | sed 's/[a-z][0-9]*/& &/'
echo "$KITTY" | sed 's/[a-z][a-z]*/& & &/'
