#!/bin/sh
if [ $# -lt 1 ]; then
    # in case of no arguments, this is default layout #
    # this creates a NEW window, leaving the last one #
    # totally unchanged, and opens an application layout #
    tmux new-window -a -n Window2
    tmux rename-window "T-macs"
    tmux split-window -h
    tmux last-pane
    tmux send-keys "emacs -nw" C-m
    tmux last-pane
    tmux split-window -p80
    tmux last-pane
    tmux split-window -h
    tmux send-keys "tty-clock" C-m
    tmux last-pane
    tmux send-keys "cal" C-m
    tmux last-pane
else 
case "$1" in
    "bottom")
	    # creates 3 pane bottom-stack #
	    tmux split-window -v
	    tmux split-window -h -p 66
	    tmux split-window -h
	    tmux select-pane -t 0
	    tmux send-keys "clear" C-m
	    ;;
    "top")
	    # creates 3 pane top-stack #
	    tmux split-window -v
	    tmux last-pane
	    tmux split-window -h -p 66
	    tmux split-window -h
	    tmux select-pane -t 0
	    tmux send-keys "clear" C-m
	    ;;
    "left")
	    # creates 3 pane left stack #
	    tmux split-window -h
	    tmux select-pane -t 0
	    tmux split-window -v -p 66
	    tmux split-window -v
	    tmux select-pane -t 0
	    tmux send-keys "clear" C-m
	    ;;
    "right")
	    # creates 3 pane right-stack #
	    tmux split-window -h
	    tmux split-window -v -p 66
	    tmux split-window -v
	    tmux select-pane -t 0
	    tmux send-keys "clear" C-m
	    ;;
########################
    *) echo "Invalid layout"
	    ;;
esac
fi
