#!/bin/bash
argv1=$1
if [ $argv1 -lt 1 ]; then
    tmux new-window -a -n Window2
    tmux rename-window "T-macs"
    tmux split-window -h
    tmux last-pane
    tmux send-keys "emacs -nw" C-m
    tmux last-pane
    tmux split-window -p80
    tmux last-pane
    tmux split-window -h
    tmux send-keys "tty-clock" C-m
    tmux last-pane
    tmux send-keys "cal" C-m
    tmux last-pane
elif [[ $argv1 == "bottom" ]]; then
    tmux split-window -v
    tmux split-window -h
    tmux select-pane -t 0
elif [[ $argv1 == "top" ]]; then
    tmux split-window -v
    tmux last-pane
    tmux split-window -h
    tmux select-pane -t 0
fi
