#!/bin/bash

monitor='xrandr | grep "VGA1 connected"'

if [ -n "$monitor" ]; then #check to see if variable is non-empty
	echo `xrandr --output VGA1 --auto --right-of LVDS1`
else
	echo `xrandr --output VGA1 --off`
fi
