#!/bin/bash

n=0
for((i=0;i<=10000;++i)) do
   if [[ $n -eq 0 ]]; then
       n=0
   elif [[ $n -eq 1 ]]; then
       n=0
   elif [[ $n -eq 2 ]]; then
       n=0
   else
       n=0
   fi
echo "at $i n is $n"
done
