#!/bin/bash

n=0
for((i=0;i<=10000;++i)) do
   if (( n == 0 )); then
       n=1
   elif (( n == 1 )); then
       n=2
   elif (( n == 2 )); then
       n=3
   else
       n=0
   fi
echo "at $i n is $n"
done
