#!/bin/bash

# ^A == "A" at the beginning of the line
# A$ == "A" at the END of the line
# A^ == "A" anywhere on the line
# $A == "A" anywhere on the line
# ^^ == "^" at the beginning of the line
# $$ == "$" at the end of the line.

cat testfile | sed -e 's/^t/T/g'
# since line 2 starts with a "t", it is capitalized.

cat testfile | sed -e 's/^[a-z]/(&)/g'
# since line 2 is lowercase, it is the matched string, and is put in parenthesis.

cat testfile | sed -e 's/at$/ow/g'
# since line 1 ends with 'at' we replace it with 'ow'.
# you could OFC use a pipe and cat to a new file with fixes:
# ie: cat <file> | sed -e 's/^regex/newpattern/g' > newfile
# to check that your changes worked correctly.

# or you can make a backup with (sed -i.bak 's/OLD_STRING/NEW_STRING/' > file
# to make a sort of 'inline' edit
